version: '2'
services:
  # My web application running django and gunicorn
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - "postgres:postgres"
    env_file: .env
    volumes:
      - ./web:/code
      - ./web/static:/usr/src/app/static
    command: /usr/local/bin/gunicorn mysite.wsgi:application -w 2 -b :8000 --reload
  # The web server
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - "web:web"
  # The database
  postgres:
    restart: always
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgrsql/data
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: django03.webfactional.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
